### ISSUE TITLE
Ansible schemas not loaded

### ISSUE THREAD

**Issue by MVKozlov** [ansible-community/vscode-ansible#50] opened 2021-03-16 11:41 UTC
I am currently trying to use this module, but I have an error: 
```
Problems loading reference 'https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json': Unable to load schema from 'https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json': No content.
```
The quick traffic debug show that server return
"304 - not modified" on load request
Cache clearing dit not help

I see two non-exclusive solutions:
- make schema path configurable
- use 'do not cache' headers on request

**Comment by lask79** [comment] 2021-03-19 20:48
I am getting the same issue.

**Comment by ssbarnea** [comment] 2021-03-19 22:32
The code that loads the url is not part of this extension, is inside vscode-yaml extension. Still it looks quite weird, i wonder if there is a problem with github itself.

**Comment by ssbarnea** [comment] 2021-03-26 12:19
I think this was caused by some networking issues with github and has nothing to do with our code. Closing at least for the moment, feel free to comment it if happens again and is not related to some outdage on github side (check their status).

**Closed by ssbarnea** 2021-03-26 12:19 UTC

**Comment by MVKozlov** [comment] 2021-03-26 13:15
I cannot agree with the network reason.
The status is OK at the moment, but I still get 304. but now, not for all files
Capture by a Fiddler:
Request
```
GET https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json HTTP / 1.1
Accepting encoding: gzip, deflate
If-None-Match: W / "fbf608e2a3bb946e932950eb49c2ba5e0404bd3a8741ee3725a9cead7a03c91e"
Host: raw.githubusercontent.com
Connection: close
```
Response
```
HTTP/1.1 304 Not Modified
Connection: close
Date: Fri, 26 Mar 2021 13:04:21 GMT
Via: 1.1 varnish
Cache-Control: max-age=300
ETag: W/"fbf608e2a3bb946e932950eb49c2ba5e0404bd3a8741ee3725a9cead7a03c91e"
X-Served-By: cache-hhn4071-HHN
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1616763861.440961,VS0,VE147
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 69598713e8f7655acbec0fd5452c1b40f9a80cf0
Expires: Fri, 26 Mar 2021 13:09:21 GMT
Source-Age: 0
```
Notice the `If-None-Match` header.
If it is explicitly set by "vscode-yaml" then it is their bug.
